### ISSUE TITLE
In 03.00.DEBUG.md there is rustled name used

### ISSUE THREAD

**Issue by rofrol** [droogmic/microrust#22]
Why it is not `microrust-start`? How was this `rustled` introduced?

**Comment by Jackbennett** [comment]
On the same page, little lower:

> The starter project I've provided to you has some extra code th..

What starter project? I can't find any other reference to `rustled` in the whole book.

Did you ever find an answer?

**Comment by rofrol** [comment]
I think this issue can be closed https://github.com/droogmic/microrust/pull/19

**Comment by rofrol** [comment]
@Jackbennett I think there is this starter project https://github.com/droogmic/microrust/tree/master/src/getting-started
